run:
  timeout: 6m
  issues-exit-code: 1
linters:
  disable-all: true
  enable:
    - goimports
    - govet
    - interfacer
    - misspell
    - structcheck
    - unconvert
issues:
  # TODO(kanata2): fix existing issues
  new: true
